        # self.king_pieces[0]=createPiece('k', 4, 0, Player.PLAYER_B, image_size)
        # white_pieces.append(createPiece('p', 4, 1, Player.PLAYER_W, image_size))
        # white_pieces.append(createPiece('r', 3, 7, Player.PLAYER_W, image_size))
        # self.king_pieces[1]=createPiece('k', 4, 7, Player.PLAYER_W, image_size)
        # white_pieces.append(createPiece('b', 1, 4, Player.PLAYER_W, image_size))
        # black_pieces.append(createPiece('p', 5, 1, Player.PLAYER_B, image_size))
        
        # self.king_pieces[0]=createPiece('k', 4, 0, Player.PLAYER_B, image_size)
        # self.king_pieces[1]=createPiece('k', 4, 7, Player.PLAYER_W, image_size)
        # black_pieces.append(createPiece('p', 4, 6, Player.PLAYER_B, image_size))
        # black_pieces.append(createPiece('b', 2, 4, Player.PLAYER_B, image_size))
        # black_pieces.append(createPiece('r', 5, 0, Player.PLAYER_B, image_size))
        # white_pieces.append(createPiece('p', 3, 6, Player.PLAYER_W, image_size))
        # white_pieces.append(createPiece('p', 0, 5, Player.PLAYER_W, image_size))